"use client";

import * as React from "react";
import { TopBar } from "@/components/navigation/TopBar";
import { Footer } from "@/components/navigation/Footer";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Scale, ShieldAlert, Tractor, ShoppingCart, Info } from "lucide-react";

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col justify-between">
      <div>
        <TopBar />
        
        <main className="max-w-4xl mx-auto px-4 py-10 md:py-14 space-y-8 select-text">
          {/* Header */}
          <div className="space-y-2 text-center md:text-left select-none">
            <Badge variant="success" className="text-[9px] font-bold px-2 py-0.5 uppercase tracking-wide">User Agreement</Badge>
            <h1 className="text-3xl font-extrabold text-foreground tracking-tight">Terms & Conditions</h1>
            <p className="text-xs text-muted-foreground">Last Updated: October 2026</p>
          </div>

          <div className="space-y-6">
            {/* Acceptance of Terms Card */}
            <Card className="p-6 space-y-4">
              <div className="flex items-center gap-2.5 pb-2.5 border-b border-border/40 select-none">
                <Scale className="h-5 w-5 text-primary shrink-0" />
                <h2 className="text-base font-bold text-foreground">1. Acceptance of Terms</h2>
              </div>
              <div className="space-y-3 text-xs text-muted-foreground leading-relaxed">
                <p>
                  By creating an account, logging in, or utilizing any features of the Krishiva platform (including direct trading, disease diagnostics, machinery rentals, and Vira AI Advisor), you explicitly agree to comply with and be bound by these Terms & Conditions.
                </p>
                <p>
                  If you disagree with any segment of these terms, you must suspend usage of the platform immediately.
                </p>
              </div>
            </Card>

            {/* Platform Usage & Disclaimers */}
            <Card className="p-6 space-y-4">
              <div className="flex items-center gap-2.5 pb-2.5 border-b border-border/40 select-none">
                <ShieldAlert className="h-5 w-5 text-primary shrink-0" />
                <h2 className="text-base font-bold text-foreground">2. Disclaimers & Responsibilities</h2>
              </div>
              <div className="space-y-3.5 text-xs text-muted-foreground leading-relaxed">
                <p>
                  Krishiva serves as an AI-augmented decision support tool. Users should act in accordance with local regulations and professional soil testing.
                </p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>
                    <strong className="text-foreground">AI Advisory Disclaimer:</strong> Advice generated by Vira AI and the crop disease model is built on probabilistic language outputs. It does not replace certified agronomist inspections.
                  </li>
                  <li>
                    <strong className="text-foreground">Agricultural Advisory Disclaimer:</strong> Weather predictions, fertilizer index metrics, and crop suggestions are provided on an &ldquo;as-is&rdquo; basis. Krishiva is not liable for harvest failures.
                  </li>
                  <li>
                    <strong className="text-foreground">Government Scheme Disclaimer:</strong> Scheme information is aggregated from public government outlets. Users must verify criteria directly with official administrative portals.
                  </li>
                </ul>
              </div>
            </Card>

            {/* Marketplace Rules */}
            <Card className="p-6 space-y-4">
              <div className="flex items-center gap-2.5 pb-2.5 border-b border-border/40 select-none">
                <ShoppingCart className="h-5 w-5 text-primary shrink-0" />
                <h2 className="text-base font-bold text-foreground">3. Direct Sourcing Marketplace Rules</h2>
              </div>
              <div className="space-y-3 text-xs text-muted-foreground leading-relaxed">
                <p>
                  The Buyer Sourcing Marketplace acts as a bridge matching farmers with certified buyers. Krishiva does not set crop pricing, inspect grain quality, or store trading stock.
                </p>
                <p>
                  Buyers and Farmers are directly responsible for executing contracts, verifying quality grades, and settling payments. Krishiva is not a party to direct trade contracts.
                </p>
              </div>
            </Card>

            {/* Rental Rules */}
            <Card className="p-6 space-y-4">
              <div className="flex items-center gap-2.5 pb-2.5 border-b border-border/40 select-none">
                <Tractor className="h-5 w-5 text-primary shrink-0" />
                <h2 className="text-base font-bold text-foreground">4. Machinery Rental Rules</h2>
              </div>
              <div className="space-y-3 text-xs text-muted-foreground leading-relaxed">
                <p>
                  Machinery Owners listing fleet items warrant that all vehicles are in roadworthy condition, fueled, and fully insured under local laws.
                </p>
                <p>
                  Farmers renting equipment agree to operate machinery responsibly, prevent damage, and return equipment on the agreed-upon date. Rental fees must be settled upon confirmation.
                </p>
              </div>
            </Card>

            {/* Accounts, updates & payments */}
            <Card className="p-6 space-y-4">
              <div className="flex items-center gap-2.5 pb-2.5 border-b border-border/40 select-none">
                <Info className="h-5 w-5 text-primary shrink-0" />
                <h2 className="text-base font-bold text-foreground">5. General Terms</h2>
              </div>
              <div className="space-y-3.5 text-xs text-muted-foreground leading-relaxed">
                <p>
                  <strong className="text-foreground">Account Suspension:</strong> Krishiva reserves the right to terminate accounts that violate marketplace trading terms or listing rules without prior notification.
                </p>
                <p>
                  <strong className="text-foreground">Future Payment Terms:</strong> While current B2B matching features are open during the demo preview, Krishiva reserves the right to charge transactional processing fees in future updates.
                </p>
                <p>
                  <strong className="text-foreground">Updates to Terms:</strong> We may revise these terms to align with platform updates. Continued usage of Krishiva after revisions constitute acceptance of modified terms.
                </p>
              </div>
            </Card>
          </div>
        </main>
      </div>

      <Footer />
    </div>
  );
}
